name: csi_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^1.0.2
  flutter_svg: ^0.17.4
  # material_design_icons_flutter: ^3.2.3895

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # url_launcher: ^5.4.10
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/home_page_bg.png
    - assets/images/drawer bg.png
    - assets/images/our feature page bg.png
    - assets/images/we create bg.png
    - assets/images/our team bg.png
    - assets/images/secondYear/aayush.jpg
    - assets/images/secondYear/abhishek.jpg
    - assets/images/secondYear/aditya.jpg
    - assets/images/secondYear/akhilesh.jpg
    - assets/images/secondYear/Anchal.jpg
    - assets/images/secondYear/anshika.jpg
    - assets/images/secondYear/arnav.jpg
    - assets/images/secondYear/ayushporwal3843.jpg
    - assets/images/secondYear/Harsh.jpg
    - assets/images/secondYear/ishika.jpg
    - assets/images/secondYear/shivam.JPG
    - assets/images/secondYear/sonakshi.jpg
    - assets/images/secondYear/vikalp.jpg
    - assets/images/secondYear/vikas.jpg
    - assets/images/thirdYear/abhishek.jpg
    - assets/images/thirdYear/rathi.jpg
    - assets/images/thirdYear/bhawana.jpg
    - assets/images/thirdYear/gaurav.jpg
    - assets/images/thirdYear/harsh.jpg
    - assets/images/thirdYear/pramod.jpg
    - assets/images/thirdYear/priyam.jpg
    - assets/images/thirdYear/saumya.jpg
    - assets/images/thirdYear/siddhartha.jpg
    - assets/images/thirdYear/subhanshu.jpg
    - assets/images/thirdYear/ujjawal.jpg
    - assets/images/fourthYear/saxena.jpeg
    - assets/images/fourthYear/aadi.jpeg
    - assets/images/fourthYear/aanchal.jpeg
    - assets/images/fourthYear/alok.jpeg
    - assets/images/fourthYear/amit.jpeg
    - assets/images/fourthYear/ankish.jpeg
    - assets/images/fourthYear/muskan.jpeg
    - assets/images/fourthYear/pragati.jpeg
    - assets/images/fourthYear/shashwat.jpeg
    - assets/images/fourthYear/vats.jpeg
    - assets/images/fourthYear/shubh.jpeg
    - assets/images/fourthYear/sonali.jpeg
    - assets/images/fourthYear/yashvi.jpeg
    - assets/images/fourthYear/yashvi.jpeg
    
    - assets/icons/menu.svg
    
    - assets/icons/facebook.svg
    
    - assets/icons/github-image.svg

    - assets/icons/linkedin.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf    
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages