/// Flutter icons Card_icons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Card_icons
///      fonts:
///       - asset: fonts/Card_icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Cardicons {
  Cardicons._();

  static const _kFontFam = 'Cardicons';
  static const _kFontPkg = null;

  static const IconData facebook_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_sign = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
